KeurNdongo/KeurNdongo/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static



urlpatterns = [
    path("admin/", admin.site.urls),
    path('user/', include('users.urls')),  # Inclure les URLs de l'application "user"
    path('annonces/', include('annonces.urls')),  # Inclure les URLs de l'application "annonces"
    path('', include('annonces.urls')),
    # Autres URLs de votre projet, si nécessaire
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KeurNdongo/users/urls.py
# user/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('inscription/', views.inscription, name='inscription'),
    path('connexion/', views.connexion, name='connexion'),
    path('mon-compte/', views.mon_compte, name='mon_compte'),
    path('favoris/ajouter/<int:annonce_id>/', views.ajouter_favoris, name='ajouter_favoris'),
    path('favoris/', views.liste_favoris, name='favoris'),
    path('favoris/supprimer/<int:favori_id>/', views.supprimer_favori, name='supprimer_favori'),
    path('locations/resilier/<int:annonce_id>/', views.resilier_location, name='resilier_location'),
    path('tableau-de-bord/', views.tableau_de_bord, name='tableau_de_bord'),
    path('deconnexion/', views.deconnexion, name='deconnexion'),
    path('supprimer_annonce/<int:annonce_id>', views.supprimer_annonce, name='supprimer_annonce') 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KeurNdongo/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    tel = models.CharField(max_length=15)
    is_student = models.BooleanField(default=True)

class Favoris(models.Model):
    annonce = models.ForeignKey('annonces.Annonce', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

KeurNdongo/users/views.py
from django.http import HttpResponse
from django.shortcuts import render
# user/views.py
from django.shortcuts import render,redirect
from annonces.models import Annonce
from .models import Favoris
from django.contrib import messages




# user/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, redirect

def connexion(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']


        # Authentification de l'utilisateur
        user = authenticate(request, username=username, password=password)
        
        #user = User.objects.get(username=username, password=password)
        if user is not None:
            context = {
            "user" : user,
        }
            # Connexion de l'utilisateur
            login(request, user)
            if (user.is_student):
                return redirect('user:mon_compte')  # Remplacez par le nom de la vue souhaitée après la connexion
            return redirect('user:tableau_de_bord')
        else:
            # Authentification échouée
            return HttpResponse("Nom d'utilisateur ou mot de passe incorrect.")
      # Rediriger vers la page d'accueil ou une autre page
    else:
        
        return render(request, 'user/connexion.html')


# user/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from users.models import User

def inscription(request):
    if request.method == 'POST':
        user = User.objects.create(
            username = request.POST['username'],
            last_name = request.POST['nom'],
            first_name = request.POST['prenom'],
            tel = request.POST['tel'],
            email = request.POST['email'],
            password = request.POST['password'],
            is_student = True, #request.POST['est_etudiant'],
         
        )
        user.set_password(request.POST['password'])
        
        user.save()
            # Connexion automatique après l'inscription
        login(request, user)
        return redirect('home')  # Rediriger vers la page d'accueil ou une autre page
    else:
        
        return render(request, 'user/inscription.html')


def ajouter_favoris(request, annonce_id):
    annonce = Annonce.objects.get(id=annonce_id)
    Favoris.objects.create(annonce=annonce, user=request.user)
    return redirect('user:favoris')

def liste_favoris(request):
    favoris = Favoris.objects.filter(user=request.user)
    return render(request, 'user/favoris_liste.html')

from django.contrib.auth.decorators import login_required
from annonces.models import Annonce

@login_required
def tableau_de_bord(request):
    proprietaire = request.user
    maisons = Annonce.objects.filter(proprietaire=proprietaire)
    nombre_maisons = maisons.count()
    nombre_maisons_louees = maisons.filter(louer=True).count()
    
    context = {
        'maisons': maisons,
        'nombre_maisons': nombre_maisons,
        'nombre_maisons_louees': nombre_maisons_louees,
        'nombre_maisons_non_louees': nombre_maisons - nombre_maisons_louees,
    }
    return render(request, 'user/tableau_de_bord.html', context)


@login_required
def mon_compte(request):
    user = request.user
    # profile_form = UserProfileForm(instance=user)
    if request.method == 'POST':
        user = request.user
        user.last_name = request.POST['nom']
        user.first_name = request.POST['prenom']
        user.tel = request.POST['tel']
        user.email = request.POST['email']
        # user.password = request.POST['password']
        user.save()
        user.set_password(request.POST['password'])
        messages.success(request, 'Informations modifiés avec succès')
        return render(request, 'user/mon_compte.html')
    else:
        annonces_locataire = Annonce.objects.filter(locataire=user)
        favoris = Favoris.objects.filter(user=user)
        
        # if request.method == 'POST':
        #     profile_form = UserProfileForm(request.POST, instance=user)
        #     if profile_form.is_valid():
        #         profile_form.save()
        #         return redirect('user:mon_compte')
        
        context = {
            'user': user,
            # 'profile_form': profile_form,
            'annonces_locataire': annonces_locataire,
            'favoris': favoris
        }
        return render(request, 'user/mon_compte.html', context)

@login_required
def supprimer_favori(request, favori_id):
    favori = Favoris.objects.get(id=favori_id)
    favori.delete()
    return redirect('user:mon_compte')

# user/views.py
@login_required
def resilier_location(request, annonce_id):
    annonce = Annonce.objects.get(id=annonce_id)
    annonce.locataire = None  # Supprimer le locataire de l'annonce
    annonce.save()
    return redirect('user:mon_compte')

def deconnexion(request):
    logout(request)
    return redirect('home')

@login_required
def supprimer_annonce(request, annonce_id):
    annonce = Annonce.objects.get(id=annonce_id)

    # Supprimer l'annonce
    annonce.delete()
    return redirect('user:tableau_de_bord')  # Rediriger vers la page d'accueil ou une autre vue

KeurNdongo/templates/user/connexion.html
{% extends 'base.html' %}
{% block content %}
<head>
	{% load static %}

	<link rel="stylesheet" href="{% static 'css/style_login.css' %}">

</head>

	<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				{% comment %} <div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Login #04</h2>
				</div> {% endcomment %}
			</div>
			<div class="row justify-content-center">
				<div class="col-md-12 col-lg-10">
					<div class="wrap d-md-flex">
						<img class="img" src=" {% static 'img/house.jpg' %}"/>
			    
						<div class="login-wrap p-4 p-md-5">
			      	<div class="d-flex">
			      		<div class="w-100">
			      			<h3 class="mb-4">Connexion</h3>
			      		</div>
								<div class="w-100">
									<p class="social-media d-flex justify-content-end">
										<a href="#" class="social-icon d-flex align-items-center justify-content-center"><span class="fa fa-facebook"></span></a>
										<a href="#" class="social-icon d-flex align-items-center justify-content-center"><span class="fa fa-twitter"></span></a>
									</p>
								</div>
			      	</div>
							<form method ="post" action="{% url 'user:connexion' %}"  class="signin-form">
								{%csrf_token%}
			      		<div class="form-group mb-3">
			      			<label class="label" for="name">Nom d'utilisateur</label>
			      			<input type="text" name="username" class="form-control" placeholder="Username" required>
			      		</div>
		            <div class="form-group mb-3">
		            	<label class="label" for="password">Mot de passe</label>
		              <input type="password"  name='password' class="form-control" placeholder="Password" required>
		            </div>
		            <div class="form-group">
		            	<button type="submit" class="form-control btn btn-primary rounded submit px-3">Sign In</button>
		            </div>
		            <div class="form-group d-md-flex">
		            	<div class="w-50 text-left">
			            	<label class="checkbox-wrap checkbox-primary mb-0">se souvenir de moi
									  <input type="checkbox" checked>
									  <span class="checkmark"></span>
										</label>
									</div>
									<div class="w-50 text-md-right">
										<a href="#">Mot de passe oublié?</a>
									</div>
		            </div>
		          </form>
		          <p class="text-center">vous n'avez pas de compte? <a  href="{% url 'user:inscription' %}">S'inscrire</a></p>
		        </div>
		      </div>
				</div>
			</div>
		</div>
	</section>

	

	</body>
	{% endblock %}

KeurNdongo/templates/user/favoris_liste.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}

KeurNdongo/templates/user/inscription.html
{% extends 'base.html' %}
{% block content %}
<head>
	{% load static %}

	<link rel="stylesheet" href="{% static 'css/style_login.css' %}">

</head>

	<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				{% comment %} <div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Login #04</h2>
				</div> {% endcomment %}
			</div>
			<div class="row justify-content-center">
				<div class="col-md-12 col-lg-10">
					<div class="wrap d-md-flex">
						<img class="img" src=" {% static 'img/house.jpg' %}"/>
			    
						<div class="login-wrap p-4 p-md-5">
			      	<div class="d-flex">
			      		<div class="w-100">
			      			<h3 class="mb-4">Inscription</h3>
			      		</div>
								<div class="w-100">
									<p class="social-media d-flex justify-content-end">
										<a href="#" class="social-icon d-flex align-items-center justify-content-center"><span class="fa fa-facebook"></span></a>
										<a href="#" class="social-icon d-flex align-items-center justify-content-center"><span class="fa fa-twitter"></span></a>
									</p>
								</div>
			      	</div>
							<form method ="post" action="{% url 'user:inscription' %}"  class="signin-form">
								{%csrf_token%}
			      		<div class="form-group mb-3">
			      			<label class="label" for="username">Nom d'utilisateur</label>
			      			<input type="text" name="username" class="form-control" placeholder="Veuillez saisir votre nom d'utilisateur" required>

                              <div class="form-group mb-3">
                                <label class="label" for="nom">Nom</label>
                                <input type="text" name="nom" class="form-control" placeholder="Entrez votre nom" required>
                            </div>
                            <div class="form-group mb-3">
                                <label class="label" for="prenom">Prénom</label>
                                <input type="text" name="prenom" class="form-control" placeholder="Entrez votre prénom" required>
                            </div>
                            <div class="form-group mb-3">
                                <label class="label" for="email">email</label>
                                <input type="email" name="email" class="form-control" placeholder="Entrez votre email" required>
                            </div>

                            <div class="form-group mb-3">
                                <label class="label" for="nom">Téléphone</label>
                                <input type="phone" name="tel" class="form-control" placeholder="Entrez votre numéro de téléphone" required>
                            </div>

                      <div class="form-group mb-3">
                          <label class="label" for="password">Mot de passe</label>
                        <input type="password"  name='password' class="form-control" placeholder="Password" required>
                      </div>

			      		</div>
		            <div class="form-group mb-3">
		            	<label class="label" for="password">confirmation de mot de passe</label>
		              <input type="password"  name='password' class="form-control" placeholder="Veuillez saisir à nouveau votre mot de passe" required>
		            </div>




                    

		            <div class="form-group">
		            	<button type="submit" class="form-control btn btn-primary rounded submit px-3">S'inscrire</button>
		            </div>
		            <div class="form-group d-md-flex">
		            	{% comment %} <div class="w-50 text-left">
			            	<label class="checkbox-wrap checkbox-primary mb-0">Remember Me
									  <input type="checkbox" checked>
									  <span class="checkmark"></span>
										</label>
									</div> {% endcomment %}
									{% comment %} <div class="w-50 text-md-right">
										<a href="#">Forgot Password</a>
									</div> {% endcomment %}
		            </div>
		          </form>
		          <p class="text-center">vous avez déjà un compte? <a  href="{% url 'user:connexion' %}">Se connecter</a></p>
		        </div>
		      </div>
				</div>
			</div>
		</div>
	</section>

	<script src="js/jquery.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/main.js"></script>

	</body>
	{% endblock %}

KeurNdongo/templates/user/mon_compte.html
<!-- user/mon_compte.html -->
{% extends 'base.html' %} <!-- Utilisez votre modèle de base si vous en avez un -->

{% block content %}
{%csrf_token%}

<div class="container">
    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
      
  <br>
        <div class="alert alert-success" role="alert" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
      {% endfor %}
    </ul>
  {% endif %}
    <div class="row gutters">
    <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
    <div class="card h-100">
        <div class="card-body">
            <div class="account-settings">
                <div class="user-profile">
                    <div class="user-avatar">
                        <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Maxwell Admin">
                    </div>
                    <h5 class="user-name">{{user.username}}</h5>
                    <h6 class="user-email">{{user.email}}</h6>
                </div>
                <div class="about">
                    {% if request.user.is_student %}
                        <h5>Profile: Etudiant</h5>
                    {% else %}
                        <h5>Profile: Propriétaire</h5>
                    {% endif %}
                    <a href="{% url 'user:deconnexion' %}">Déconnexion</a>
                </div>
            </div>  
        </div>
    </div>
    </div>
    <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
    <div class="card h-100">
        <div class="card-body">
            <div class="row gutters">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <h6 class="mb-2 text-primary">Informations personnels</h6>
                </div>
                <form method ="post" action="{% url 'user:mon_compte' %}" >
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        {%csrf_token%}
                        <label class="label" for="nom">Nom</label>
                        <input type="text" name="nom" class="form-control" value={{user.last_name}} required>
                            </div>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label class="label" for="prenom">Prénom</label>
                        <input type="text" name="prenom" class="form-control" value={{user.first_name}} required>
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="eMail">Email</label>
                        <input type="email" name='email' class="form-control" id="eMail" value={{user.email}}>
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="phone">Phone</label>
                        <input type="text" name ='tel' class="form-control" id="phone" value={{user.tel}}>
                    </div>
                </div>

                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="password">Mot de passe</label>
                        <input type="password" name='password' class="form-control" id="eMail" value={{user.password}}>
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    <div class="form-group">
                        <label for="password1">Confirmer le mot de passe</label>
                        <input type="password" name ='password1' class="form-control" id="phone" value={{user.password}} placeholder='mot de passe'>
                    </div>
                </div>
                
            </div>
            
            <div class="row gutters">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <div class="text-right">
                        {% comment %} <button type="submit" id="submit" name="submit" class="btn btn-secondary">Modifier</button> {% endcomment %}
                        <button type="submit" id="submit" name="submit" class="btn btn-primary">Mettre à jour</button>
                    </div>
                </div>
            </div>
        </form>
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                <h6 class="mb-2 text-primary">Vos favoris</h6>
            </div>
            
            {% for favoris in favoris %}
    <div class="col-xs-12 col-sm-6 col-md-4">
      <article class="card">
        <div class="card-block text-xs-center head">
          <h4 class="card-title">{{ favoris.annonce.titre }} </h4>
          <h6 class="card-subtitle">{{ favoris.annonce.ville }}, {{ annonce.prix }} CFA</h6>
        </div>
        <figure>
          <img src="{{favoris.annonce.image.url}}" class="img-fluid hidden-sm-up" alt="appartement à vendre">
          <img src="{{favoris.annonce.image.url}}" class="img-fluid hidden-xs-down hidden-lg-up" alt="appartement à vendre">
          <img src="{{favoris.annonce.image.url}}" class="img-fluid hidden-md-down" alt="appartement à vendre">
        </figure>
        <div class="card-block text-xs-center">
          <p class="card-text">{{ favoris.annonce.description }}</p>
          <figure class="description">
            <span><i class="fa fa-bed" aria-hidden="true"></i> {{ favoris.annonce.ville }}</span>
            <span><i class="fa fa-paper-plane" aria-hidden="true"></i>  {{favoris.annonce.quartier }} </span>
            <span><i class="fa fa-tint" aria-hidden="true"></i> {{ favoris.annonce.standing }} </span>
          </figure>
          <a href="#" class="card-link"><i class="fa fa-eye m-r-1" aria-hidden="true"></i>Voir</a>
          <button class="btn btn-primary m-r-1"><i class="fa fa-star" aria-hidden="true"></i> Favoris</button>
          <button class="btn btn-success">Louer</button>
        </div>
      </article>
    </div>
    {% empty %}
            <p>Aucun favori enregistré.<p>
    {% endfor %}


    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <h6 class="mb-2 text-primary">Vos locations</h6>
    </div>
        {% for location in annonces_locataire %}
        <div class="col-xs-12 col-sm-6 col-md-4">
          <article class="card">
            <div class="card-block text-xs-center head">
              <h4 class="card-title">{{ location.annonce.titre }} </h4>
              <h6 class="card-subtitle">{{ location.annonce.ville }}, {{ annonce.prix }} CFA</h6>
            </div>
            <figure>
              <img src="{{location.annonce.image.url}}" class="img-fluid hidden-sm-up" alt="appartement à vendre">
              <img src="{{location.annonce.image.url}}" class="img-fluid hidden-xs-down hidden-lg-up" alt="appartement à vendre">
              <img src="{{location.annonce.image.url}}" class="img-fluid hidden-md-down" alt="appartement à vendre">
            </figure>
            <div class="card-block text-xs-center">
              <p class="card-text">{{ location.annonce.description }}</p>
              <figure class="description">
                <span><i class="fa fa-bed" aria-hidden="true"></i> {{ location.annonce.ville }}</span>
                <span><i class="fa fa-paper-plane" aria-hidden="true"></i>  {{location.annonce.quartier }} </span>
                <span><i class="fa fa-tint" aria-hidden="true"></i> {{ location.annonce.standing }} </span>
              </figure>
              <a href="#" class="card-link"><i class="fa fa-eye m-r-1" aria-hidden="true"></i>Voir</a>
              <button class="btn btn-primary m-r-1"><i class="fa fa-star" aria-hidden="true"></i> Favoris</button>
              <button class="btn btn-success">Louer</button>
            </div>
          </article>
        </div>
        {% empty %}
                <p>Aucune location<p>
        {% endfor %}
    
            </div>
        </div>

    </div>
    </div>
    </div>
    </div>
{% endblock %}

KeurNdongo/templates/user/tableau_de_bord.html
{% extends 'base.html' %}

{% block content %}
<br><br>
<div class="row">
    <div class="col-xl-3 col-md-6">
        <div class="card bg-pattern">
            <div class="card-body">
                <div class="float-right">
                    <i class="fa fa-archive text-primary h4 ml-3"></i>
                </div>
                <h5 class="font-size-20 mt-0 pt-1">{{ nombre_maisons  }}</h5>
                {% if nombre_maisons > 1 %}
                    <p class="text-muted mb-0">Maisons</p>
                {% else %}
                    <p class="text-muted mb-0">Maison</p>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6s">
        <div class="card bg-pattern">
            <div class="card-body">
                <div class="float-right">
                    <i class="fa fa-th text-primary h4 ml-3"></i>
                </div>
                <h5 class="font-size-20 mt-0 pt-1">{{ nombre_maisons_louees }}</h5>
                {% if nombre_maisons_louees > 1 %}
                    <p class="text-muted mb-0">Maisons louées</p>
                {% else %}
                    <p class="text-muted mb-0">Maison louée</p>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-pattern">
            <div class="card-body">
                <div class="float-right">
                    <i class="fa fa-file text-primary h4 ml-3"></i>
                </div>
                <h5 class="font-size-20 mt-0 pt-1">{{ nombre_maisons_non_louees }}</h5>
                {% if nombre_maisons_non_louees > 1 %}
                    <p class="text-muted mb-0">Maisons non louées</p>
                {% else %}
                    <p class="text-muted mb-0">Maison non louée</p>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
          <div class="card-body">
            <div class="d-flex justify-content-between mb-3">
                <a href="{% url 'ajouter' %}" class="btn btn-danger" type="button"><i class="fa fa-plus mr-1"></i>Ajouter</a>
              <a href="{% url 'user:mon_compte' %}" class="btn btn-danger" type="button"><i class="fa fa fa-user mr-1"></i>Mon compte</a>
            </div>
          </div>
    </div>
</div>
<!-- end row -->

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive project-list">
                    <table class="table project-table table-centered table-nowrap">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Maisons</th>
                                <th scope="col">Date d'ajout</th>
                                <th scope="col">Statut</th>
                                <th scope="col">Locataire</th>
                                <th scope="col">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for maison in maisons%}
                                <tr>
                                    <th scope="row">{{ maison.id }}</th>
                                    <td>
                                        <a href="#">{{ maison.titre }}</a>
                                    </td>

                                    <td>{{ maison.date_creation|date:"SHORT_DATE_FORMAT" }}</td>
                                    <td>
                                        {% if maison.louer %}
                                            <span class="text-success font-12"><i class="mdi mdi-checkbox-blank-circle mr-1"></i> Louée </span>
                                        {% else %}
                                            <span class="text-danger font-12"><i class="mdi mdi-checkbox-blank-circle mr-1"></i>Non Louée </span>
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if maison.louer %}
                                            {{ maison.locataire.username }}
                                        {% else %}
                                            <span class="text-muted">    ------      </span>
                                        {% endif %}
                                    </td>
                            

                                    <td>
                                        <div class="action">
                                            <a href="#" class="text-success mr-4" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit"> <i class="fa fa-pencil h5 m-0"></i></a>
                                            <a href="{% url 'user:supprimer_annonce' annonce_id=maison.id  %}" class="text-danger" data-toggle="tooltip" data-placement="top" title="" data-original-title="Close"> <i class="fa fa-remove h5 m-0"></i></a>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- end project-list -->

                
            </div>
        </div>
    </div>
</div>
<!-- end row -->
</div>

{% endblock %}