KeurNdongo/KeurNdongo/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static



urlpatterns = [
    path("admin/", admin.site.urls),
    path('user/', include('users.urls')),  # Inclure les URLs de l'application "user"
    path('annonces/', include('annonces.urls')),  # Inclure les URLs de l'application "annonces"
    path('', include('annonces.urls')),
    # Autres URLs de votre projet, si nécessaire
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KeurNdongo/users/urls.py
# user/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('inscription/', views.inscription, name='inscription'),
    path('connexion/', views.connexion, name='connexion'),
    path('mon-compte/', views.mon_compte, name='mon_compte'),
    path('favoris/ajouter/<int:annonce_id>/', views.ajouter_favoris, name='ajouter_favoris'),
    path('favoris/', views.liste_favoris, name='favoris'),
    path('favoris/supprimer/<int:favori_id>/', views.supprimer_favori, name='supprimer_favori'),
    path('locations/resilier/<int:annonce_id>/', views.resilier_location, name='resilier_location'),
    path('tableau-de-bord/', views.tableau_de_bord, name='tableau_de_bord'),
    path('deconnexion/', views.deconnexion, name='deconnexion'),
    path('supprimer_annonce/<int:annonce_id>', views.supprimer_annonce, name='supprimer_annonce') 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KeurNdongo/templates/agences.html
<!doctype html>
<html class="no-js" lang="fr">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Lille Immo</title>
  <meta name="description" content="Trouvez les coordonnées de l'agence la plus proche de chez-vous">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="apple-touch-icon" href="apple-touch-icon.png">
  <!-- Place favicon.ico in the root directory -->
  <link rel="icon" type="image/ico" href="favicon.ico">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css" integrity="sha384-MIwDKRSSImVFAZCVLtU0LMDdON6KVCrZHyVQQj6e8wIEJkW4tvwqXrbMIya1vriY" crossorigin="anonymous">
  <link rel="stylesheet" href="css/normalize.css">
  <link rel="stylesheet" href="css/main.css">
  <link href="https://fonts.googleapis.com/css?family=Prompt%7cOpen+Sans%7cReem+Kufi" rel="stylesheet">
  <script src="https://use.fontawesome.com/c6f237cddf.js"></script>
  <script src="js/vendor/modernizr-2.8.3.min.js"></script>
</head>
<body>
  <!--[if lt IE 8]>
  <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
  <![endif]-->

  <!--

  ~~~~~~~~~Start of the top head content~~~~~~~~~~~~~

-->

<!-- Start of the header -->
<header id="top">

  <!-- Back to top button -->
  <a href="#top" class="m-b-1"><i class="fa fa-arrow-up fa-lg hidden-sm-up pull-xs-right" aria-hidden="true"></i></a>
  <a href="#top" class="m-b-1 m-r-1"><i class="fa fa-arrow-up fa-2x hidden-sm-down pull-sm-right" aria-hidden="true"></i></a>

  <!-- Boxed layout inside the header -->
  <div class="container">
    <div class="row">
      <!-- Left logo -->
      <figure class="col-xs-5">
        <img src="img/logo_immo_large.jpg" alt="logo lille immo" class="img-fluid hidden-md-down">
        <img src="img/logo_immo_medium.jpg" alt="logo lille immo" class="img-fluid hidden-xs-down hidden-lg-up">
        <img src="img/logo_immo_small.jpg" alt="logo lille immo" class="img-fluid hidden-sm-up">
      </figure>
      <!-- Main title on the right -->
      <aside class="col-xs-7 text-xs-center">
        <h1>Des experts à votre service</h1>
      </aside>
    </div>
  </div>

</header>
<!-- end of the header -->

<!-- Start of the navigation -->
<nav>

  <!-- Personnal space icon -->
  <a href="#">
    <aside class="pull-xs-right m-r-2" id="personal_space">
      <i class="fa fa-user fa-3x m-r-1 hidden-xs-down" aria-hidden="true"></i>
      <i class="fa fa-user fa-2x m-r-1 hidden-sm-up" id="small_user" aria-hidden="true"></i>
      <span>Espace<br>personnel</span>
    </aside>
  </a>
  <!-- Navigation -->
  <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
    &#9776;
  </button>
  <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
    <ul class="nav navbar-nav">
      <li class="nav-item m-x-1">
        <a class="nav-link" href="index.html">Accueil<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item m-x-1">
        <a class="nav-link" href="achat.html">Achat</a>
      </li>
      <li class="nav-item m-x-1">
        <a class="nav-link" href="location.html">Location</a>
      </li>
      <li class="nav-item m-x-1">
        <a class="nav-link" href="presentation.html">Présentation</a>
      </li>
      <li class="nav-item m-x-1 on">
        <a class="nav-link" href="agences.html">Nos agences</a>
      </li>
    </ul>
  </div>

</nav>
<!-- End of the navigation -->

<!-- Start of the jumbotron with main image -->
<div class="jumbotron p-t-1 text-xs-center">
  <span class="pull-xs-right appeal">Vous aussi trouvez votre place !</span>
</div>
<!-- End of the jumbotron with main image -->

<!--

~~~~~~~~~End of the top head content~~~~~~~~~~~~~

-->

<!--

~~~~~~~~~Start of the main content~~~~~~~~~~~~~

-->

<!-- Start of section with boxed content -->
<section class="container">

  <h2>3 agences dans la métrople</h2>
  <p>Avec des bureaux à Lille, Roubaix et Villeneuve d'Ascq, notre agence immobilière est présente dans les grands centres immobliers.
  Placés au coeur de notre secteur d'activité, nous nous déplaçons rapidement et ne sommes jamais loins de vous. N'hésitez pas à nous contacter
ou à venir directement nous rencontrer.</p>

<!-- Google map -->
  <iframe src="https://www.google.com/maps/d/embed?mid=18_MlsGRJLDUQEIrI_AMSmFS0_xc"></iframe>

<!-- Column content -->
  <div class="row m-t-3">

<!-- Agencies location -->
    <div class="col-xs-12 col-sm-6">
      <h3>Agence de Roubaix</h3>
      <p>47 Boulevard Gambetta</p>
      <p><i class="fa fa-phone green" aria-hidden="true"></i><a href="tel:000000000">   ## ## ## ## ##</a></p>
      <p><i class="fa fa-envelope purple" aria-hidden="true"></i><a href="mailto:agenceexempel@gmail.com">   agenceexempel@gmail.com</a></p>
      <p>Ouvert du lundi au vendre, de 8h00 à 12h00 et de 13h00 à 18h00</p>
      <h3>Agence de Lille</h3>
      <p>100 Boulevard Louis XIV</p>
      <p><i class="fa fa-phone green" aria-hidden="true"></i><a href="tel:000000000">   ## ## ## ## ##</a></p>
      <p><i class="fa fa-envelope purple" aria-hidden="true"></i><a href="mailto:agenceexempel@gmail.com">   agenceexempel@gmail.com</a></p>
      <p>Ouvert du lundi au vendre, de 8h00 à 12h00 et de 13h00 à 18h00</p>
      <h3>Agence de Villeneuve d'Ascq</h3>
      <p>16 Avenue du pont de bois</p>
      <p><i class="fa fa-phone green" aria-hidden="true"></i><a href="tel:000000000">   ## ## ## ## ##</a></p>
      <p><i class="fa fa-envelope purple" aria-hidden="true"></i><a href="mailto:agenceexempel@gmail.com">   agenceexempel@gmail.com</a></p>
      <p>Ouvert du lundi au vendre, de 8h00 à 12h00 et de 13h00 à 18h00</p>
    </div>

<!-- Contact form -->
    <div class="col-xs-12 col-sm-6">
      <h3>Nous contacter</h3>
      <form class="m-b-2">
        <fieldset class="form-group">
          <label for="firstname">Prénom</label>
          <input type="text" class="form-control" id="firstname" name="user_firstname">
          <label class="m-t-1" for="lastname">Nom</label>
          <input type="text" class="form-control" id="lastname" name="user_lastname">
          <label class="m-t-1" for="mail">Adresse mail</label>
          <input type="email" class="form-control" id="mail" name="user_email">
          <small class="text-muted">Ces informations resteront confidentielles.</small>
        </fieldset>

        <fieldset class="form-group">
          <label for="agency">Quelle agence souhaitez-vous contacter ?</label>
          <select class="form-control" id="agency" name="contact_agency">
            <option value="information_generale">Lille</option>
            <option value="devis">Roubaix</option>
            <option value="rendez_vous">Villeneuve d'Ascq</option>
          </select>
        </fieldset>

        <fieldset class="form-group">
          <label for="message">Vous pouvez indiquer votre message</label>
          <textarea class="form-control" id="message" name="user_message" rows="3"></textarea>
        </fieldset>
        <button type="submit" class="btn" id="contact_button">Envoyer</button>
      </form>
    </div>
  </div>

</section>

<!--

~~~~~~~~~End of the main content~~~~~~~~~~~~~

-->

<!--

~~~~~~~~~Start of the footer~~~~~~~~~~~~~

-->

<footer class="m-t-3">

  <!-- Start of the section -->
  <section class="container p-t-1 p-x-1 text-xs-center">
    <h4>Lille Immo en bref</h4>
    <p>Lille Immo c'est 5 agences réparties au travers de la métropole et toujours à votre service. Vous pouvez contacter l'agence la plus proche de chez vous via la rubrique nos agences ou contacter notre siège au 03 20 ## ## ##</p>
    <!-- Footer navigation -->
    <nav class="row">
      <ul class="nav navbar-nav text-xs-center col-xs-9">
        <li class="nav-item m-x-1">
          <a class="nav-link" href="index.html">Accueil<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item m-x-1">
          <a class="nav-link" href="achat.html">Achat</a>
        </li>
        <li class="nav-item m-x-1">
          <a class="nav-link" href="location.html">Location</a>
        </li>
        <li class="nav-item m-x-1">
          <a class="nav-link" href="presentation.html">Présentation</a>
        </li>
        <li class="nav-item m-x-1">
          <a class="nav-link" href="agences.html">Nos agences</a>
        </li>
      </ul>
      <!-- Social medias icons -->
      <figure class="col-xs-3 m-t-1">
        <a href="#">
          <i class="fa fa-facebook-official fa-2x m-r-1" aria-hidden="true"></i>
        </a>
        <a href="#">
          <i class="fa fa-twitter fa-2x m-r-2" aria-hidden="true"></i>
        </a>
      </figure>
    </nav>
    <!-- Copyright paragraphe -->
    <p>Lille Immo 2016. &copy;Une réalisation <a href="https://thomgo.github.io/portfolio/" target="_blank">Thomas Gossart</a></p>
  </section>

</footer>

<!--

~~~~~~~~~End of the footer~~~~~~~~~~~~~

-->

<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<script>window.jQuery || document.write('<script src="js/vendor/jquery-1.12.0.min.js"><\/script>')</script>
<script src="js/plugins.js"></script>
<script src="js/main.js"></script>

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
  (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
    function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
    e=o.createElement(i);r=o.getElementsByTagName(i)[0];
    e.src='https://www.google-analytics.com/analytics.js';
    r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
    ga('create','UA-XXXXX-X','auto');ga('send','pageview');
  </script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/js/bootstrap.min.js" integrity="sha384-ux8v3A6CPtOTqOzMKiuo3d/DomGaaClxFYdCu2HPMBEkf6x2xiDyJ7gkXU0MWwaD" crossorigin="anonymous"></script>
</body>
</html>

KeurNdongo/templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="fr">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Lille Immo</title>
  <meta name="description" content="Retrouvez sur cette page tous nos biens à la location">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="apple-touch-icon" href="apple-touch-icon.png">
  <!-- Place favicon.ico in the root directory -->
  <link rel="icon" type="image/ico" href="favicon.ico">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css" integrity="sha384-MIwDKRSSImVFAZCVLtU0LMDdON6KVCrZHyVQQj6e8wIEJkW4tvwqXrbMIya1vriY" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link rel="stylesheet" href="{% static 'css/style_login.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Prompt%7cOpen+Sans%7cReem+Kufi" rel="stylesheet">
  <script src="https://use.fontawesome.com/c6f237cddf.js"></script>
  <script src="{% static 'js/vendor/modernizr-2.8.3.min.js'%}"></script>
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
</head>
<body>
  <!--[if lt IE 8]>
  <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
  <![endif]-->

  <!--

  ~~~~~~~~~Start of the top head content~~~~~~~~~~~~~

-->

<!-- Start of the header -->
<header id="top">

  <!-- Back to top button -->
  <a href="#top" class="m-b-1"><i class="fa fa-arrow-up fa-lg hidden-sm-up pull-xs-right" aria-hidden="true"></i></a>
  <a href="#top" class="m-b-1 m-r-1"><i class="fa fa-arrow-up fa-2x hidden-sm-down pull-sm-right" aria-hidden="true"></i></a>

  <!-- Boxed layout inside the header -->
  {% comment %} <div class="container">
    <div class="row">
      <!-- Left logo -->
      <figure class="col-xs-5">
        <img src="{% static 'img/logo_immo_medium.jpg' %}" alt="logo lille immo" class="img-fluid hidden-md-down">
        <img src="{% static 'img/logo_immo_medium.jpg' %}" alt="logo lille immo" class="img-fluid hidden-xs-down hidden-lg-up">
        <img src="{% static 'img/logo_immo_small.jpg' %}" alt="logo lille immo" class="img-fluid hidden-sm-up">
      </figure>
      <!-- Main title on the right -->
      <aside class="col-xs-7 text-xs-center">
        <h1>Des experts à votre service</h1>
      </aside>
    </div>
  </div> {% endcomment %}

</header>
<!-- end of the header -->

<!-- Start of the navigation -->
<nav>

  <!-- Personnal space icon -->
  {% if request.user.is_authenticated %}
    {% if request.user.is_student %}
      <a href="{% url 'user:mon_compte' %}">
        <aside class="pull-xs-right m-r-2" id="personal_space">
          <i class="fa fa-user fa-3x m-r-1 hidden-xs-down" aria-hidden="true"></i>
          <i class="fa fa-user fa-2x m-r-1 hidden-sm-up" id="small_user" aria-hidden="true"></i>
          <span>Espace<br>personnel</span>
        </aside>
      </a>
    {% else %}
    <a href="{% url 'user:tableau_de_bord' %}">
      <aside class="pull-xs-right m-r-2" id="personal_space">
        <i class="fa fa-user fa-3x m-r-1 hidden-xs-down" aria-hidden="true"></i>
        <i class="fa fa-user fa-2x m-r-1 hidden-sm-up" id="small_user" aria-hidden="true"></i>
        <span>Tableau <br> de bord</span>
      </aside>
    </a>

    {% endif %}
  {% else %}
    <div class="pull-xs-right m-r-2" id="personal_space">
        
      <a type='button' class="btn btn-outline-primary m-r-1" style="margin: 10px;" href="{% url 'user:connexion' %}">Se connecter</a>
      <a class="btn btn-success" style="margin: 10px;" href="{% url 'user:inscription' %}">S'inscrire</a>
    </div>
  {% endif %}
  <div class="pull-xs-right m-r-2">
  <form class="form-inline my-2 my-lg-0">
    <input class="form-control mr-sm-2"style="margin: 10px;" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </div>
  </form>
  <!-- Navigation -->
  <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
    &#9776;
  </button>
  <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
    <ul class="nav navbar-nav">
      {% comment %} <li class="nav-item m-x-1">
        <a class="nav-link" href="{% url 'home' %}">Accueil<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item m-x-1">
        <a class="nav-link" href="achat.html">Achat</a>
      </li> {% endcomment %}
      <li class="nav-item m-x-1 on">
        <a class="nav-link" href="{% url 'home' %}">Accueil</a>
      </li>
      {% comment %} <li class="nav-item m-x-1">
        <a class="nav-link" href="presentation.html">Présentation</a>
      </li>
      <li class="nav-item m-x-1">
        <a class="nav-link" href="agences.html">Nos agences</a>
      </li> {% endcomment %}
    </ul>
  </div>

</nav>
<!-- End of the navigation -->
{% block content %}
{% endblock %}

<!--
~~~~~~~~Start of the footer~~~~~~~~~~~~~
-->

<footer class="m-t-3">

  <!-- Start of the section -->
  <section class="container p-t-1 p-x-1 text-xs-center">
    <h4>Lille Immo en bref</h4>
    <p>Lille Immo c'est 5 agences réparties au travers de la métropole et toujours à votre service. Vous pouvez contacter l'agence la plus proche de chez vous via la rubrique nos agences ou contacter notre siège au 03 20 ## ## ##</p>
    <!-- Footer navigation -->
    <nav class="row">
      <ul class="nav navbar-nav text-xs-center col-xs-9">
        <li class="nav-item m-x-1">
          <a class="nav-link" href="{% url 'home' %}">Accueil<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item m-x-1">
          <a class="nav-link" href="achat.html">Achat</a>
        </li>
        <li class="nav-item m-x-1">
          <a class="nav-link" href="location.html">Location</a>
        </li>
        <li class="nav-item m-x-1">
          <a class="nav-link" href="presentation.html">Présentation</a>
        </li>
        <li class="nav-item m-x-1">
          <a class="nav-link" href="agences.html">Nos agences</a>
        </li>
      </ul>
      <!-- Social medias icons -->
      <figure class="col-xs-3 m-t-1">
        <a href="#">
          <i class="fa fa-facebook-official fa-2x m-r-1" aria-hidden="true"></i>
        </a>
        <a href="#">
          <i class="fa fa-twitter fa-2x m-r-2" aria-hidden="true"></i>
        </a>
      </figure>
    </nav>
    <!-- Copyright paragraphe -->
    <p>Lille Immo 2016. &copy;Une réalisation <a href="https://thomgo.github.io/portfolio/" target="_blank">Thomas Gossart</a></p>
  </section>

</footer>

<!--

~~~~~~~~~End of the footer~~~~~~~~~~~~~

-->

<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<script>window.jQuery || document.write('<script src="js/vendor/jquery-1.12.0.min.js"><\/script>')</script>
<script src="{% static 'js/plugins.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>



<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
  (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
    function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
    e=o.createElement(i);r=o.getElementsByTagName(i)[0];
    e.src='https://www.google-analytics.com/analytics.js';
    r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
    ga('create','UA-XXXXX-X','auto');ga('send','pageview');
  </script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/js/bootstrap.min.js" integrity="sha384-ux8v3A6CPtOTqOzMKiuo3d/DomGaaClxFYdCu2HPMBEkf6x2xiDyJ7gkXU0MWwaD" crossorigin="anonymous"></script>
</body>
</html>